services:

  nginx:
    image: nginx:alpine
    container_name: shiny-proxy
    ports:
      - "4000:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - shiny-net
    depends_on:
      - shinyproxy
    restart: unless-stopped

  shinyproxy:
    image: openanalytics/shinyproxy:3.2.4
    container_name: shinyproxy
    user: root
    volumes:
      - ./application.yml:/opt/shinyproxy/application.yml:ro
      - ./.env:/opt/shinyproxy/.env:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shiny-net
    restart: unless-stopped

volumes:
  shared-outputs:
    name: shared-outputs

networks:
  shiny-net:
    name: shiny-net