services:

  nginx:
    image: nginx:alpine
    container_name: shiny-proxy
    ports:
      - "4000:443"    # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - shiny1
      - shiny2
      - shiny3
      - shiny4
    restart: unless-stopped

  shiny1:
    build: .
    image: modulo-reportes
    env_file: .env
    volumes:
      - shared-outputs:/srv/shiny-server/outputs
    restart: unless-stopped

  shiny2:
    image: modulo-reportes
    env_file: .env
    volumes:
      - shared-outputs:/srv/shiny-server/outputs
    restart: unless-stopped

  shiny3:
    image: modulo-reportes
    env_file: .env
    volumes:
      - shared-outputs:/srv/shiny-server/outputs
    restart: unless-stopped

  shiny4:
    image: modulo-reportes
    env_file: .env
    volumes:
      - shared-outputs:/srv/shiny-server/outputs
    restart: unless-stopped

volumes:
  shared-outputs:
