events {}

http {
  upstream shiny_backend {
    ip_hash;  # sticky sessions
    server shiny:3838;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://shiny_backend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 300s;
      proxy_send_timeout 300s;
    }
  }
}
